services:
  web:
    build: .
    container_name: stockify-django
    command: sh -c "python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    container_name: stockify-postgres
    image: postgres:13
    environment:
      POSTGRES_DB: stockify_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db_data: